export const ADD_STORE_START = 'ADD_STORE_START';
export const ADD_STORE_SUCCESS = 'ADD_STORE_SUCCESS';
export const ADD_STORE_FAIL = 'ADD_STORE_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const FETCH_STORES_START = 'FETCH_STORES_START';
export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';
export const FETCH_STORES_FAIL = 'FETCH_STORES_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_INIT_START = 'AUTH_INIT_START';
export const AUTH_INIT_SUCCESS = 'AUTH_INIT_SUCCESS';
export const AUTH_INIT_FAIL = 'AUTH_INIT_FAIL';
export const AUTH_INIT = 'AUTH_INIT';

export const FETCH_SLOTS_START = 'FETCH_SLOTS_START';
export const FETCH_SLOTS_SUCCESS = 'FETCH_SLOTS_SUCCESS';
export const FETCH_SLOTS_FAIL = 'FETCH_SLOTS_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const CREATE_BOOKING_START = 'CREATE_BOOKING_START';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAIL = 'CREATE_BOOKING_FAIL';

export const FETCH_BOOKING_START = 'FETCH_BOOKING_START';
export const FETCH_BOOKING_SUCCESS = 'FETCH_BOOKING_SUCCESS';
export const FETCH_BOOKING_FAIL = 'FETCH_BOOKING_FAIL';

export const RESET_BOOKING_PROPS = 'RESET_BOOKING_PROPS';

export const FETCH_LOCATION_START = 'FETCH_LOCATION';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAIL = 'FETCH_LOCATION_FAIL';


export const FETCH_SLOT_AVAILABILITY_START = 'FETCH_SLOT_AVAILABILITY_START';
export const FETCH_SLOT_AVAILABILITY_SUCCESS = 'FETCH_SLOT_AVAILABILITY_SUCCESS';
export const FETCH_SLOT_AVAILABILITY_FAIL = 'FETCH_SLOT_AVAILABILITY_FAIL';

export const FETCH_QR_CODE_START = 'FETCH_QR_CODE_START';
export const FETCH_QR_CODE_SUCCESS = 'FETCH_QR_CODE_SUCCESS';
export const FETCH_QR_CODE_FAIL = 'FETCH_QR_CODE_FAIL';

export const COMPLETE_BOOKING_VERIFICATION_START = 'COMPLETE_BOOKING_VERIFICATION_START';
export const COMPLETE_BOOKING_VERIFICATION_SUCCESS = 'COMPLETE_BOOKING_VERIFICATION_SUCCESS';
export const COMPLETE_BOOKING_VERIFICATION_FAIL = 'COMPLETE_BOOKING_VERIFICATION_FAIL';

